### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by tomasborges** [mauriceqch/pcc_geo_cnn_v2#2]
Dear author,

I am trying to get you results to compare with my own, but I'm having trouble to download the whole results .ZIP file. The download keeps on restarting and never finishes.
Could you share a separete link with just the data.csv, bitrates and objective metric values for all models, point clouds and metrics (D1/D2) ?

Regards,
Tomas Borges

**Comment by mauriceqch** [comment]
Hi @tomasborges,

Thanks for reporting this issue.
I will reupload the files to a better hosting location.
Meanwhile, I have uploaded the CSV file with the requested data:
https://github.com/mauriceqch/pcc_geo_cnn_v2/blob/master/data.csv

Best,
Maurice Quach

**Comment by mauriceqch** [comment]
The full data is now available on Google Drive. I hope this will solve the issue.
https://drive.google.com/file/d/18uHmr0ZpgFLeL9Y5TUFTsQkRfz4XpQdJ/view?usp=sharing

**Comment by tomasborges** [comment]
Now everything seems to be working. Thanks!
